name: "chest_xray"
backend: "python"
max_batch_size: 8

input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]  # [channels, height, width]
  }
]

output [
  {
    name: "predictions"
    data_type: TYPE_FP32
    dims: [ 14 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
